export interface AlgorithmDetail {
  id: string;
  name: string;
  category: 'sorting' | 'searching' | 'tree' | 'graph' | 'hashing' | 'linear';
  timeBest: string;
  timeAverage: string;
  timeWorst: string;
  spaceComplexity: string;
  stable: boolean;
  inPlace: boolean;
  adaptive: boolean;
  method: string;
  useCases: string[];
  description: string;
}

export const ALGORITHM_DETAILS: AlgorithmDetail[] = [
  // ── Sorting ───────────────────────────────────────────────────
  {
    id: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    timeBest: 'O(n)',
    timeAverage: 'O(n²)',
    timeWorst: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    adaptive: true,
    method: 'Exchanging',
    useCases: ['Nearly sorted data', 'Educational purposes', 'Small datasets'],
    description: 'Repeatedly swaps adjacent elements if they are in the wrong order.',
  },
  {
    id: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    timeBest: 'O(n²)',
    timeAverage: 'O(n²)',
    timeWorst: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    adaptive: false,
    method: 'Selection',
    useCases: ['Small datasets', 'Memory-constrained environments', 'When writes are expensive'],
    description: 'Finds the minimum element and moves it to the front repeatedly.',
  },
  {
    id: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    timeBest: 'O(n)',
    timeAverage: 'O(n²)',
    timeWorst: 'O(n²)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    adaptive: true,
    method: 'Insertion',
    useCases: ['Small datasets', 'Nearly sorted data', 'Online sorting (streaming)'],
    description: 'Builds a sorted array by inserting each element into its correct position.',
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    timeBest: 'O(n log n)',
    timeAverage: 'O(n log n)',
    timeWorst: 'O(n log n)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: false,
    adaptive: false,
    method: 'Merging',
    useCases: ['Large datasets', 'Linked lists', 'External sorting', 'Guaranteed performance'],
    description: 'Divides the array into halves, sorts each, then merges them back together.',
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    timeBest: 'O(n log n)',
    timeAverage: 'O(n log n)',
    timeWorst: 'O(n²)',
    spaceComplexity: 'O(log n)',
    stable: false,
    inPlace: true,
    adaptive: false,
    method: 'Partitioning',
    useCases: ['General-purpose sorting', 'Arrays (cache-friendly)', 'Standard library default'],
    description: 'Selects a pivot and partitions the array around it recursively.',
  },
  {
    id: 'heap-sort',
    name: 'Heap Sort',
    category: 'sorting',
    timeBest: 'O(n log n)',
    timeAverage: 'O(n log n)',
    timeWorst: 'O(n log n)',
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    adaptive: false,
    method: 'Selection',
    useCases: ['Memory-constrained sorting', 'Priority scheduling', 'Guaranteed O(n log n)'],
    description: 'Builds a max-heap and repeatedly extracts the maximum element.',
  },

  // ── Searching ─────────────────────────────────────────────────
  {
    id: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    timeBest: 'O(1)',
    timeAverage: 'O(n)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Sequential',
    useCases: ['Unsorted data', 'Small datasets', 'Single occurrence lookup'],
    description: 'Checks each element sequentially until the target is found.',
  },
  {
    id: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    timeBest: 'O(1)',
    timeAverage: 'O(log n)',
    timeWorst: 'O(log n)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Divide & Conquer',
    useCases: ['Sorted arrays', 'Dictionary lookup', 'Database indexing'],
    description: 'Repeatedly divides the search space in half to find the target.',
  },

  // ── Trees ─────────────────────────────────────────────────────
  {
    id: 'bst-search',
    name: 'BST Search',
    category: 'tree',
    timeBest: 'O(1)',
    timeAverage: 'O(log n)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(h)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Tree Traversal',
    useCases: ['Dynamic datasets', 'Range queries', 'Ordered data retrieval'],
    description: 'Navigates left or right in a BST based on comparison with the target.',
  },
  {
    id: 'bst-insert',
    name: 'BST Insertion',
    category: 'tree',
    timeBest: 'O(1)',
    timeAverage: 'O(log n)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(h)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Tree Insertion',
    useCases: ['Building search trees', 'Dynamic sorted collections', 'Symbol tables'],
    description: 'Inserts a new node at the correct position maintaining BST property.',
  },
  {
    id: 'tree-traversal',
    name: 'Tree Traversal (DFS)',
    category: 'tree',
    timeBest: 'O(n)',
    timeAverage: 'O(n)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(h)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Depth-First',
    useCases: ['Expression evaluation', 'Serialization', 'File system traversal'],
    description: 'Visits all nodes in a tree using In-order, Pre-order, or Post-order.',
  },

  // ── Graphs ────────────────────────────────────────────────────
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graph',
    timeBest: 'O(V + E)',
    timeAverage: 'O(V + E)',
    timeWorst: 'O(V + E)',
    spaceComplexity: 'O(V)',
    stable: true,
    inPlace: false,
    adaptive: false,
    method: 'Level-order',
    useCases: ['Shortest path (unweighted)', 'Social network analysis', 'Web crawlers'],
    description: 'Explores all neighbors at the current depth before moving deeper.',
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graph',
    timeBest: 'O(V + E)',
    timeAverage: 'O(V + E)',
    timeWorst: 'O(V + E)',
    spaceComplexity: 'O(V)',
    stable: true,
    inPlace: false,
    adaptive: false,
    method: 'Backtracking',
    useCases: ['Cycle detection', 'Topological sort', 'Maze solving', 'Connected components'],
    description: 'Explores as far as possible along a branch before backtracking.',
  },

  // ── Hashing ───────────────────────────────────────────────────
  {
    id: 'hash-insert',
    name: 'Hash Table Insert',
    category: 'hashing',
    timeBest: 'O(1)',
    timeAverage: 'O(1)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: false,
    adaptive: false,
    method: 'Hashing',
    useCases: ['Caching', 'Database indexing', 'Symbol tables', 'Deduplication'],
    description: 'Maps keys to array indices via a hash function for constant-time access.',
  },
  {
    id: 'hash-lookup',
    name: 'Hash Table Lookup',
    category: 'hashing',
    timeBest: 'O(1)',
    timeAverage: 'O(1)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Hashing',
    useCases: ['Key-value stores', 'Frequency counting', 'Membership testing'],
    description: 'Retrieves a value by computing the hash of its key.',
  },

  // ── Linear Structures ────────────────────────────────────────
  {
    id: 'stack-ops',
    name: 'Stack Push/Pop',
    category: 'linear',
    timeBest: 'O(1)',
    timeAverage: 'O(1)',
    timeWorst: 'O(1)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'LIFO',
    useCases: ['Undo systems', 'Expression parsing', 'Function call stack', 'Backtracking'],
    description: 'Last-In-First-Out structure for push and pop operations.',
  },
  {
    id: 'queue-ops',
    name: 'Queue Enqueue/Dequeue',
    category: 'linear',
    timeBest: 'O(1)',
    timeAverage: 'O(1)',
    timeWorst: 'O(1)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'FIFO',
    useCases: ['Task scheduling', 'BFS implementation', 'Print queues', 'Message buffers'],
    description: 'First-In-First-Out structure for enqueue and dequeue operations.',
  },
  {
    id: 'linked-list-ops',
    name: 'Linked List Ops',
    category: 'linear',
    timeBest: 'O(1)',
    timeAverage: 'O(n)',
    timeWorst: 'O(n)',
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: true,
    adaptive: false,
    method: 'Pointer-based',
    useCases: ['Dynamic memory allocation', 'Implementing stacks/queues', 'Polynomial arithmetic'],
    description: 'Insert, delete, and search operations on a pointer-linked chain of nodes.',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', color: '#6366F1' },
  { id: 'sorting', label: 'Sorting', color: '#F59E0B' },
  { id: 'searching', label: 'Searching', color: '#10B981' },
  { id: 'tree', label: 'Trees', color: '#8B5CF6' },
  { id: 'graph', label: 'Graphs', color: '#EC4899' },
  { id: 'hashing', label: 'Hashing', color: '#06B6D4' },
  { id: 'linear', label: 'Linear', color: '#F97316' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];
